### ISSUE TITLE
Examples folder

### ISSUE THREAD

**Issue by maxspahn** [mahaarbo/urdf2casadi#8] opened 2021-04-01 11:50 UTC
Hi everyone,

I enjoy using urdf2casadi in general. 
However, there is a few things that currently do not work properly in the provided examples.

- python3 support: The example in the README.md was changed to python3 in b1a9f7d
- dependencies: The example are dependent on other libraries such as rbdl, kdl_parser_py, etc -> this is not in the installation guide
- root link with inertia: Once all of the dependencies are installed, kdl fails to load gantry.urdf for example duo to a rootlink with inertia

Maybe these issues can be addressed in the future. 
I am also willing to help if required or desired.

Best,
Max.

**Comment by mahaarbo** [comment] 2021-04-06 10:16
Hi Max!

Glad to hear you enjoy the library in general.

>     * python3 support: The example in the README.md was changed to python3 in [b1a9f7d](https://github.com/mahaarbo/urdf2casadi/commit/b1a9f7d653afda980b2a9bd498d889213548f970)

What exactly is the problem there? Are there other places where this library fails with python3? It was intended to work with both python2 and python3, but the numerical and timing examples which were used to generate the results in the article have not been updated to reflect this. 

>     * dependencies: The example are dependent on other libraries such as rbdl, kdl_parser_py, etc -> this is not in the installation guide

The numerical testing examples which were used to generate the results in the article are dependent on `rbdl`, `kdl_parser_py`, and `pybullet` as stated here: [numerical/README](https://github.com/mahaarbo/urdf2casadi/blob/master/examples/numerical/README.md) but I see that it this information is missing from the timing folder. Currently `rbdl` seems to be having some [issue](https://github.com/rbdl/rbdl/issues/29) with their python wrapper, so perhaps it is best to move numerical and timing examples to a `article_results` folder? This might make it clearer that they were intended for the article, and can be used to test for oneself whether things work as expected with your desired URDF. Another alternative is to split the examples into a separate repository so as to not have too much data in the main repo.

>     * root link with inertia: Once all of the dependencies are installed, kdl fails to load gantry.urdf for example duo to a rootlink with inertia

This is an issue in `kdl_parser`, and does not affect the algorithm in this library, if I'm not mistaken.

Any contributions that further develop the library are greatly appreciated! Things that haven't been done but could be interesting include: 
 * More examples (e.g. clarifying examples)
 * Testing on other systems (ROS vs non-ROS, windows)
 * Support for kinematic trees rather than just kinematic chains

**Comment by maxspahn** [comment] 2021-04-06 14:23
Hi mahaarbo,

I update all the python print statements to be compatible with python3. I will shortly make a pull request.

I didn't see these requirements in the README file, I am sorry for that.

As I am working with the franka emika panda, I might add an example with that in the future.

Best,
Max.

**Comment by mahaarbo** [comment] 2021-04-13 08:38
If there's nothing left to add at this moment, I'll close this issue. Thanks for the PR!

**Closed by mahaarbo** 2021-04-13 08:38 UTC
